// Live assistant name -> id lookup, replacing the public/voice-assistants.json
// snapshot as the source of truth.
//
// The snapshot was regenerated by hand every few days. Anything created or
// renamed inside that window had no working link, which is how a published
// assistant ends up showing "There is no assistant matching this URL."
// Fetching from Vapi at request time closes the window to the cache TTL below.
//
// The snapshot stays in the bundle as a fallback for when this route is
// unavailable (missing secret, Vapi outage), so a failure here degrades to the
// old behaviour instead of an empty page.

// GET /assistant caps limit at 1000 and has no cursor; pagination past that is
// a createdAt walk. Verified against https://api.vapi.ai/api-json, 2026-08-19.
const PAGE_LIMIT = 1000;
const MAX_PAGES = 10;

// Long enough that a demo being clicked around does not hammer Vapi, short
// enough that April can rename an assistant and share the link right after.
const CACHE_SECONDS = 60;

const listAssistants = async (apiKey) => {
  const out = [];
  let before = null;

  for (let page = 0; page < MAX_PAGES; page++) {
    const url = new URL("https://api.vapi.ai/assistant");
    url.searchParams.set("limit", String(PAGE_LIMIT));
    if (before) url.searchParams.set("createdAtLt", before);

    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (!res.ok) {
      throw new Error(`Vapi list assistants failed: ${res.status}`);
    }

    const batch = await res.json();
    if (!Array.isArray(batch) || batch.length === 0) break;
    out.push(...batch);
    if (batch.length < PAGE_LIMIT) break;

    // The response is ordered newest first, so the oldest createdAt in this
    // batch is where the next page starts.
    const oldest = batch[batch.length - 1]?.createdAt;
    if (!oldest || oldest === before) break;
    before = oldest;
  }

  // Only name and id reach the browser. An assistant object also carries the
  // system prompt, tool config and provider settings, none of which belong in
  // a public response.
  return out
    .filter((a) => a && a.id && a.name)
    .map((a) => ({ name: a.name, id: a.id }));
};

export const onRequestGet = async ({ request, env, waitUntil }) => {
  const apiKey = env.VAPI_PRIVATE_KEY;
  if (!apiKey) {
    // 503 rather than 500: the client treats this as "fall back to the
    // snapshot", which is exactly right when the secret is not configured yet.
    return Response.json(
      { error: "VAPI_PRIVATE_KEY is not configured" },
      { status: 503 },
    );
  }

  const cache = caches.default;
  const cacheKey = new Request(new URL("/api/assistants", request.url), {
    method: "GET",
  });

  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  let assistants;
  try {
    assistants = await listAssistants(apiKey);
  } catch (error) {
    console.error("Live assistant lookup failed:", error);
    return Response.json({ error: "Upstream lookup failed" }, { status: 503 });
  }

  const response = Response.json(assistants, {
    headers: {
      "Cache-Control": `public, max-age=${CACHE_SECONDS}`,
    },
  });

  waitUntil(cache.put(cacheKey, response.clone()));
  return response;
};
